import Head from 'next/head';
import Image from 'next/image';
import { Main } from '../styles/Globals Elements';
import Header from '@/components/Header/Header';
import { Presentation,
  Section1,
  Buttons,
  CardsContainer,
  ServiceCard,
  CircleImage,
  Section2 } from '@/styles/Index Elements';
import { Link, animateScroll as scroll } from "react-scroll";

export default function Home() {
  return (
    <>
      <Head>
        <title>TEMUJ - Inicio</title>
        <meta name="description" content="Generated by Matias Minchaca" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <Presentation>
          <h1>
            ¡Bienvenido!
          </h1>
          <p>
          Somos TEMUJ, tu socio de confianza en servicios y obras. Con nuestra experiencia y compromiso con la calidad, hacemos realidad tus proyectos de construcción y renovación, uno a la vez.
          </p>
          <Buttons>
            <Link
              activeClass="active"
              to="section1"
              spy={true}
              smooth={true}
              offset={-70}
              duration={500}
            >
              {'¿Qué ofrecemos?'}
            </Link>
            <Link
              activeClass="active"
              to="section2"
              spy={true}
              smooth={true}
              offset={-70}
              duration={500}
            >
              {'Contactanos'}
            </Link>
          </Buttons>
        </Presentation>
        <Section1 id="section1">
          <h2>
            Nuestros servicios
          </h2>
          <CardsContainer>
            <ServiceCard back='true'>
              <CircleImage>
                <Image src='/images/enchufe.png' width={40} height={40} title='enchufe'/>
              </CircleImage>
              <p>Electricidad Gral.</p>
            </ServiceCard>
            <ServiceCard back='false'>
              <CircleImage>
                <Image src='/images/pared-de-ladrillo.png' width={40} height={40} title='construccion'/>
              </CircleImage>
              <p>Construcción</p>
            </ServiceCard>
            <ServiceCard back='true'>
              <CircleImage>
                <Image src='/images/soldadura.png' width={40} height={40} title='soldadura'/>
              </CircleImage>
              <p>Soldadura</p>
            </ServiceCard>
            <ServiceCard back='false'>
              <CircleImage>
                <Image src='/images/plomeria.png' width={40} height={40} title='plomeria'/>
              </CircleImage>
              <p>Plomería</p>
            </ServiceCard>
            <ServiceCard back='true'>
              <CircleImage>
                <Image src='/images/pintura.png' width={40} height={40} title='pintura'/>
              </CircleImage>
              <p>Pintura</p>
            </ServiceCard>
            <ServiceCard back='false'>
              <CircleImage>
                <Image src='/images/mesero.png' width={40} height={40} title='mesero'/>
              </CircleImage>
              <p>Meseros</p>
            </ServiceCard>
            <ServiceCard back='true'>
              <CircleImage>
                <Image src='/images/limpieza.png' width={40} height={40} title='limpieza'/>
              </CircleImage>
              <p>Limpieza</p>
            </ServiceCard>
          </CardsContainer>
          <div className='CC'>
            <h3>
              Las 24 horas del dia.
            </h3>
            <h3>
              Garantia 100% asegurada.
            </h3>
            <h3>
              Servicios de confianza.
            </h3>
          </div>
        </Section1>
        <Section2 id='section2'>

        </Section2>
      </Main>
    </>
  )
}
